<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<NoWarn>$(NoWarn);SYSLIB1045</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="11.11.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
		<PackageReference Include="AutoMapper" Version="16.2.0" />
		<PackageReference Include="MediatR" Version="12.4.1" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain\EasyReach_Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="CQRS\Querys\AdminIdentity\" />
	</ItemGroup>

</Project>

